imap:
  url: ${IMAP_URL}
  username: ${IMAP_USERNAME}
  password: ${IMAP_PASSWORD}
  includedFolders: ${IMAP_INCLUDED_FOLDERS:}
  excludedFolders: ${IMAP_EXCLUDED_FOLDERS:}
email:
  update-interval: ${EMAIL_UPDATE_INTERVAL:240}
  storing:
    strategy: ${EMAIL_STORING_STRATEGY:PAPERLESS}
    folder: ${EMAIL_STORING_FOLDER:emails}
paperless:
  url: ${PAPERLESS_URL:}
  token: ${PAPERLESS_TOKEN:}
  tags: ${PAPERLESS_TAGS:}
server:
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    generate-ddl: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql